99Cats/cats99/config/routes.rb
Rails.application.routes.draw do
  post 'cat_rental_requests/approve'
  post 'cat_rental_requests/deny'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

  resources :cat_rental_requests, only: [:new, :create]
end

99Cats/cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#

class Cat < ActiveRecord::Base
  COLORS = %w[black white brown orange grey yellow red]

  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: %w(M F) }
  validates :color, inclusion: {in: COLORS}

  has_many :rentals,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    Date.today.year - self.birth_date.year
  end
end

99Cats/cats99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  status     :string           default("PENDING"), not null
#  start_date :date             not null
#  end_date   :date             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, :inclusion => { in: ["PENDING", "APPROVED", "DENIED"]}
  validate :date_order, :overlapping_approved_requests

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  def date_order
    order = end_date > start_date

    unless order
      self.errors['date_order'] << "End date has to be after start date!"
    end
  end

  def overlapping_requests
    # CatRentalRequest.where("#{self.start_date} < start_date AND start_date < #{self.end_date}
    # OR #{self.start_date} < end_date AND end_date < #{self.end_date}
    # OR start_date < #{self.start_date} AND #{self.start_date} < end_date").where(:cat_id => self.cat_id)
    selfs_dates = [self.start_date, self.end_date, self.start_date, self.end_date, self.start_date, self.end_date]
    arr = CatRentalRequest.where("? <= start_date AND start_date <= ? OR
    ? <= end_date AND end_date <= ? OR start_date <= ? AND ? <= end_date", *selfs_dates).where('cat_id = ?', self.cat_id)
  end

  def overlapping_approved_requests
    overlaps = overlapping_requests.where("status = ?", 'APPROVED')

    unless overlaps.empty?
      self.errors['overlapping_requests'] << "Can't make an overlapping request"
    end
  end

  def overlapping_pending_requests
    overlaps = overlapping_requests.where("status = ?", 'PENDING').where('id !=  ?', self.id)
  end

  def approve!
    CatRentalRequest.transaction do
      overlapping_pending_requests.each{|rental| rental.deny!}
      self.status = 'APPROVED'
      self.save
    end
  end

  def deny!
    self.status = 'DENIED'
    self.save
  end
end

99Cats/cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @catrental = CatRentalRequest.new
    render :new
  end

  def create
    @catrental = CatRentalRequest.new(cat_rental_params)
    @catrental.save!
    redirect_to cats_url
  end

  def approve
    @catrental = CatRentalRequest.find_by(id: params[:id])
    @catrental.approve!
    cat = Cat.find_by(id: @catrental.cat_id)
    redirect_to cat_url(cat)
  end

  def deny
    @catrental = CatRentalRequest.find_by(id: params[:id])
    @catrental.deny!
    cat = Cat.find_by(id: @catrental.cat_id)
    redirect_to cat_url(cat)
  end

  private

  def cat_rental_params
    params.require(:cat_rental_requests).permit(:id, :cat_id, :start_date, :end_date)
  end
end

99Cats/cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.save
    render :show
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    @cat.update(cat_params)

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :description, :sex)
  end
end

99Cats/cats99/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

99Cats/cats99/app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

99Cats/cats99/app/helpers/catrentalrequest_helper.rb
module CatrentalrequestHelper
end

99Cats/cats99/app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

99Cats/cats99/app/views/cat_rental_requests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Schedule a cat rental</title>
  </head>
  <body>
    <form action="/cat_rental_requests" method="post">
      <label for="cat_id">Cat</label>
      <select id="cat_id" name="cat_rental_requests[cat_id]">
        <% Cat.all.each do |cat| %>
          <option value="<%=cat.id%>"><%=cat.name%></option>
        <% end %>
      </select>

      <label for="start_date">Start Date</label>
      <input type="date" name="cat_rental_requests[start_date]" id="start_date">

      <label for="end_date">End Date</label>
      <input type="date" name="cat_rental_requests[end_date]" id="end_date">

      <input type="submit" value="Submit Request">
    </form>
  </body>
</html>

99Cats/cats99/app/views/cats/_form.html.erb
<%action_url = (action == :new) ? cats_url : cat_url(cat)%>
<form action="<%=action_url%>" method="post">
  <%= auth_token %>
  <% if action == :edit%>
    <input type='hidden' name='_method' value='patch'>
  <% end %>
  <label for="name">Name</label>
  <input type="text" name="cat[name]" id="name" value="<%=cat.name %>">

  <label for='sex'>Sex</label>
  M<input type="radio" name="cat[sex]" value='M' <%= "checked" if cat.sex == 'M'%>>
  F<input type="radio" name="cat[sex]" value='F' <%= "checked" if cat.sex == 'F'%>>

  <label for="color">Color</label>
  <select id = "color" name = "cat[color]">
    <option value="none" selected disabled>Choose a color</option>
    <option value="black" <%= "selected" if cat.color == 'black'%>>Black</option>
    <option value="white" <%= "selected" if cat.color == 'white'%>>White</option>
    <option value="brown" <%= "selected" if cat.color == 'brown'%>>Brown</option>
    <option value="orange" <%= "selected" if cat.color == 'orange'%>>Orange</option>
    <option value="grey" <%= "selected" if cat.color == 'orange'%>>Grey</option>
    <option value="yellow" <%= "selected" if cat.color == 'yellow'%>>Yellow</option>
    <option value="red" <%= "selected" if cat.color == 'red'%>>Red</option>
  </select>

  <label for="birth_date">Birth day</label>
  <input type="date" name="cat[birth_date]" id="birth_date" value="<%=cat.birth_date%>">

  <label for="description">Description</label>
    <textarea name="cat[description]"><%=cat.description%></textarea>
  <input type="submit" value="Submit Cat">
</form>

99Cats/cats99/app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add a new cat</title>
  </head>
  <body>
    <%= render "form", cat: @cat, action: :edit%>
  </body>
</html>

99Cats/cats99/app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>

    <h1>CATS</h1>
    <% @cats.each do |cat| %>

    <p>
      <%= link_to "#{cat.name}", cat_url(cat)%>
      <%= link_to "Edit", edit_cat_url(cat) %>
    </p>

    <% end %>
    <h2><%= link_to "Make a fresh new cat", new_cat_url%></h2>
    <h3><%= link_to "Make a reservation", new_cat_rental_request_url%></h3>
  </body>

  <% content_for :footer do %>
    <p> This is the index! </p>
  <% end %>
</html>

99Cats/cats99/app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add a new cat</title>
  </head>
  <body>
    <%= render "form", cat: @cat, action: :new%>
  </body>

  <% content_for :footer do %>
    <p> Let's make a new cat! </p>
  <% end %>
</html>

99Cats/cats99/app/views/cats/show.html.erb
<!-- :birth_date, :color, :name, :sex -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Cat details<h2>

    <h2>
      <table>
        <tr>
          <td>Birthday</td>
          <td>Age</td>
          <td>Color</td>
          <td>Name</td>
          <td>Sex</td>
          <td>Description</td>
        </tr>
        <tr>
          <td><%= @cat.birth_date %></td>
          <td><%= @cat.age %></td>
          <td><%= @cat.color %></td>
          <td><%= @cat.name %></td>
          <td><%= @cat.sex %></td>
          <td><%= @cat.description %></td>
        </tr>
      </table>
    </h2>

    <h2>Requests</h2>
    <table>
      <tr>
        <td>Start Date</td>
        <td>End Date</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <% @cat.rentals.sort_by{|rental| rental.start_date}.each do |rental| %>
        <tr>
          <td><%= rental.start_date %></td>
          <td><%= rental.end_date %></td>

          <td><%= button_to "Approve", cat_rental_requests_approve_url, {id: rental.id}  %>
            <form method="post" action="<%=cat_rental_requests_approve_url%>">
              <input value="Approve" type="submit"/>
            </form>
          </td>

        </tr>
        <% end %>
    </table>

    <h3>
      <p> <%= link_to "Edit #{@cat.name}", edit_cat_url(@cat)%></p>
      <p> <%= link_to "New Cat", new_cat_url%></p>
      <p> <%= link_to "Cats", cats_url%></p>
    </h3>
  </body>

  <% content_for :footer do %>
    <p> This is a cat's show page </p>
  <% end %>
</html>

99Cats/cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
    This is the greatest cat rental site ever made.
    <%= yield :footer %>
  </footer>
</html>